package juuxel.vineflowerforloom.api;

import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.io.InputStream;

/**
 * A decompiler source provides a Vineflower jar from an arbitrary location.
 *
 * @see SourceFactory default source types
 * @since 1.11.0
 */
public interface DecompilerSource {
    /**
     * Opens an input stream to the provided decompiler jar file.
     * Closing the stream is the responsibility of the caller.
     *
     * @return the opened input stream
     * @throws IOException if an IO error occurred
     */
    InputStream open() throws IOException;

    /**
     * {@return the provided decompiler version, or null if it should be autogenerated}
     */
    @Nullable String getProvidedVersion();

    /**
     * {@return the resolved decompiler version, or null if it should be autogenerated}
     *
     * <p>For Maven {@code -SNAPSHOT} artifacts, the resolved version should refer to the individual dated snapshot release.
     *
     * <p>By default, returns the {@linkplain #getProvidedVersion provided decompiler version}.
     *
     * @since 1.10.0
     * @throws IOException if an IO error occurred
     */
    default @Nullable String getResolvedVersion() throws IOException {
        return getProvidedVersion();
    }
}
