package juuxel.loomquiltflower.api;

import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.io.InputStream;

public interface QuiltflowerSource {
    InputStream open() throws IOException;

    /**
     * {@return the provided Quiltflower version, or null if it should be autogenerated}
     */
    @Nullable String getProvidedVersion();
}
