name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [
          17 # Minimum (0.11+)
        ]
        loom: [
          # Upstream
          "fabric-loom:0.8-SNAPSHOT",  # Barely alive
          "fabric-loom:0.9-SNAPSHOT",  # Barely alive
          "fabric-loom:0.11-SNAPSHOT", # Barely alive
          "fabric-loom:0.12-SNAPSHOT", # Barely alive
          "fabric-loom:1.0-SNAPSHOT", # Barely alive
          "fabric-loom:1.1-SNAPSHOT", # Stable
          #"fabric-loom:1.2-SNAPSHOT", # Stable

          # Arch
          "dev.architectury.loom:0.7.4-SNAPSHOT",  # Barely alive
          "dev.architectury.loom:0.10.0-SNAPSHOT", # Barely alive (but needed to test Arch decompiler API)
          "dev.architectury.loom:0.11.0-SNAPSHOT", # Barely alive
          "dev.architectury.loom:0.12.0-SNAPSHOT", # Barely alive
          "dev.architectury.loom:1.0-SNAPSHOT", # Barely alive
          "dev.architectury.loom:1.1-SNAPSHOT", # Stable
          #"dev.architectury.loom:1.2-SNAPSHOT", # Experimental

          # Quilt
          "org.quiltmc.loom:0.12.+", # Barely alive
          "org.quiltmc.loom:1.0.+",  # Barely alive
          "org.quiltmc.loom:1.1.+",  # Barely alive
          #"org.quiltmc.loom:1.2.+",  # Stable
        ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x gradlew
      - name: Build with Gradle
        id: build
        run: ./gradlew printEscapedLoomVariantForActions build --stacktrace
        env:
          TEST_LOOM_VARIANT: ${{ matrix.loom }}
        if: |
          !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.pull_request.title, '[ci skip]')
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: ${{ steps.build.outputs.loom }} Results
          path: build/reports/
